# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0838df54ac5dc68914bf57ab027e977e53304904080e00c429a2f052fd0bb9fae828bfbc6db8fd6d64bfa0f2990b483e26279ec54512ad9012a9ab626bb5a6b4

test:
  secret_key_base: ea4a593704ef4b40fb5f5e7b95f829ec0710bfd3361fbae9fe52511fde3e3bfb5d17b84576cffe983d4fc22d2fb6bb7d48e4a6ebea48571fd2c6cf182b0af841

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
